---

#- debug:
#    msg:
#    - "vault_out_dir: {{ vault_out_dir }}"
#    - "vault_check_out_script: {{ vault_check_out_script }}"
#    - "vault_secret_id: {{ vault_secret_id }}"


- name: "Checkout secret files from ANZ HashiCorp Vault into {{ vault_out_dir }} directory"
  script: "{{ vault_check_out_script }} --secret {{ vault_secret_id }} --role {{ vault_role_id }} --host {{ vault_host }} --env {{ vault_env }} --dp_sa {{ vault_dp_sa }} --dp_cert {{ vault_dp_cert }} --dp_key {{ vault_dp_key }} --secret_folder {{ outer_item }} --out_dir {{ vault_out_dir }}"
  args:
    executable: "{{ python_path }}"
    chdir: "{{ git_repo_directory }}"
  tags:
     - vault
     - packaging
     - bps
     - connectivity
