---

- name: Download Vault secret archive file
  get_url:
    url: "{{ artifactory_url }}/artifactory/{{ artifactory_repository }}/dependencies/hashicorp/vault/secret_id/{{ vault_env }}/approle_{{ vault_env }}_read_write_0/current/secret_id.zip"
    dest: "{{ powercurve_directory }}/key/vault/"
    validate_certs : false
    timeout: 120
  register: download_archive_file


- name: Unarchive a file with extra options
  unarchive:
    src: "{{ powercurve_directory }}/key/vault/secret_id.zip"
    dest: "{{ powercurve_directory }}/key/vault"
    extra_opts:
      - "-P"
      -  "{{ artifactory_password }}"
  register: unarchive_result

- name: Get secret_id
  shell: grep -w secret_id secret_id.info.json | awk '{print $2;}' | cut -d'"' -f 2
  args:
    chdir: "{{ powercurve_directory }}/key/vault"
  register: secret_id

- debug: var=secret_id.stdout


