---

- name: Create credential for OpenShift by {{OPENSHIFT_TEST_USER_ID}} user
  command: "oc login https://{{openshift_cdp_baseUrl}}:{{openshift_cdp_port}} --username={{OPENSHIFT_TEST_USER_ID}} --password={{OPENSHIFT_TEST_USER_PWD}}"

- name: Switch default workspace to {{openshift_cdp_nameSpace}}
  command: "oc project {{openshift_cdp_nameSpace}}"