galaxy_info:
  author: ANZ CDP of FCRD
  description: Common Decision Platform
  company: Australia and New Zealand Banking Group Limited

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.4

  platforms:
  - name: Red Hat Enterprise Linux Server
    versions:
    - 7.6 (Maipo)

  galaxy_tags: [ANZ, FCRD, CDP]

dependencies: []